version: "2"

services:
  myapp:
    build: . 
    restart: always
    ports:
      - 3002:3002
      - 3001:3001

  prometheus:
    image: prom/prometheus:v2.40.4 
    ports:
      - 9090:9090
    volumes:
      - ./pkg/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.3.0 
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin 
    volumes:
      - ./pkg/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana:/var/lib/grafana

# if you want to persist the data, you can use a volume
# to store the data outside the container
volumes:
  grafana: